micronaut:
  application:
    name: order
  server:
    port: 8080

kafka:
  bootstrap:
    servers: ${KAFKA_SERVERS:`localhost:9092`}

zeebe:
  enabled: true
  broker: ${ZEEBE_HOST:127.0.0.1}:${ZEEBE_PORT:26500}
